# Generates Rec.709 conversion LUTs for Fujifilm F-Log and F-Log2.
#
# Log decode constants taken VERBATIM from Fujifilm's official datasheets:
#   F-Log  Data Sheet Ver.1.2  https://dl.fujifilm-x.com/technical-data/F-Log_DataSheet_E_Ver.1.2.pdf
#   F-Log2 Data Sheet Ver.1.1  https://dl.fujifilm-x.com/technical-data/F-Log2_DataSheet_E_Ver.1.1.pdf
#
# Run:  powershell -ExecutionPolicy Bypass -File make-flog-luts.ps1
# (Uses compiled C# — PowerShell function-call overhead is far too slow for 33^3 entries.)

$ErrorActionPreference = 'Stop'

Add-Type -TypeDefinition @"
using System;
using System.Text;
using System.IO;

public static class FLogLut
{
    // F-Gamut -> Rec.709. F-Gamut shares Rec.2020 primaries, so this is the
    // standard BT.2020 -> BT.709 matrix (both D65).
    static readonly double[,] M = {
        { 1.660491, -0.587641, -0.072850},
        {-0.124550,  1.132900, -0.008350},
        {-0.018154, -0.100597,  1.118751}
    };

    const double W = 8.0;      // tone-map white point, in scene-linear
    static double gain = 1.0;  // solved so 18% grey maps back to 18%

    static double ToneRaw(double x) {
        if (x < 0) return 0.0;
        return x * (1.0 + x / (W * W)) / (1.0 + x);
    }
    static double Tone(double x) {
        double v = ToneRaw(x * gain);
        return v > 1.0 ? 1.0 : v;
    }
    // Rec.709 OETF
    static double Enc(double x) {
        if (x < 0) x = 0; if (x > 1) x = 1;
        if (x < 0.018) return 4.5 * x;
        return 1.099 * Math.Pow(x, 0.45) - 0.099;
    }

    public static void Build(string path, string title,
        double a, double b, double c, double d, double e, double f, double cut2, int N)
    {
        // solve the 18%-grey-preserving gain
        gain = 1.0;
        for (int i = 0; i < 500; i++) {
            double r = ToneRaw(0.18 * gain);
            if (r <= 0) break;
            gain *= (0.18 / r);
        }

        // decode is per-channel and identical -> precompute the 1D table
        double[] dec = new double[N];
        for (int i = 0; i < N; i++) {
            double v = (double)i / (N - 1);
            dec[i] = (v >= cut2) ? Math.Pow(10.0, ((v - d) / c)) / a - b / a
                                 : (v - f) / e;
        }

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("# " + title);
        sb.AppendLine("# Log decode: Fujifilm official datasheet constants (exact).");
        sb.AppendLine("# Gamut: F-Gamut (BT.2020 primaries) -> BT.709, D65.");
        sb.AppendLine("# Display: extended-Reinhard shoulder (W=" + W + "), 18% grey preserved, Rec.709 OETF.");
        sb.AppendLine("# Generated by make-flog-luts.ps1");
        sb.AppendLine("TITLE \"" + title + "\"");
        sb.AppendLine("LUT_3D_SIZE " + N);
        sb.AppendLine("DOMAIN_MIN 0.0 0.0 0.0");
        sb.AppendLine("DOMAIN_MAX 1.0 1.0 1.0");

        for (int bi = 0; bi < N; bi++)
        for (int gi = 0; gi < N; gi++)
        for (int ri = 0; ri < N; ri++)
        {
            double lr = dec[ri], lg = dec[gi], lb = dec[bi];
            double r = M[0,0]*lr + M[0,1]*lg + M[0,2]*lb;
            double g = M[1,0]*lr + M[1,1]*lg + M[1,2]*lb;
            double bb= M[2,0]*lr + M[2,1]*lg + M[2,2]*lb;
            sb.AppendLine(
                Enc(Tone(r)).ToString("F6", System.Globalization.CultureInfo.InvariantCulture) + " " +
                Enc(Tone(g)).ToString("F6", System.Globalization.CultureInfo.InvariantCulture) + " " +
                Enc(Tone(bb)).ToString("F6", System.Globalization.CultureInfo.InvariantCulture));
        }
        File.WriteAllText(path, sb.ToString());
    }
}
"@

$OutDir = $PSScriptRoot
$N = 33

[FLogLut]::Build((Join-Path $OutDir "FLog_to_Rec709.cube"),  "F-Log to Rec.709",
    0.555556, 0.009468, 0.344676, 0.790453, 8.735631, 0.092864, 0.100537775223865, $N)

[FLogLut]::Build((Join-Path $OutDir "FLog2_to_Rec709.cube"), "F-Log2 to Rec.709",
    5.555556, 0.064829, 0.245281, 0.384316, 8.799461, 0.092864, 0.100686685370811, $N)

Write-Host "done"
